from svg_elements.svg_root_element import SVGRootElement
from svg_elements.svg_rect_element import SVGRectElement
from svg_elements.svg_text_element import SVGTextElement
from svg_elements.svg_circle_element import SVGCircleElement